### ISSUE TITLE
Could not get code signature for running application

### ISSUE THREAD

**Issue by throrin19** [kitze/JSUI#111]
I have an error when I launch JSUI on my mac :

```
Unhandled Error
Error: Could not get code signature for running application
    at initUpdater (/Applications/JSUI.app/Contents/Resources/app.asar/node_modules/update-electron-app/index.js:47:15)
    at App.opts.electron.app.isReady.opts.electron.app.on (/Applications/JSUI.app/Contents/Resources/app.asar/node_modules/update-electron-app/index.js:32:43)
```

I used the version 0.0.18 in an macOS 10.13.5

**Comment by nicooprat** [comment]
Seems related to the fact that the app in unsigned: https://github.com/electron/electron/issues/7476. On Mac it also prevents the app from being opened the first time, unless getting through Security preferences and forcing it to be opened.

**Comment by shockw4ver** [comment]
If it's not neccessay for you to use the autoUpdate service, #112 may give you a way to resolve this.

**Comment by kitze** [comment]
Try this release:
https://github.com/kitze/JSUI/releases/tag/v0.0.18
