### ISSUE TITLE
Application not opening on Mac OS High Sierra 10.13.4

### ISSUE THREAD

**Issue by mykel347** [kitze/JSUI#114]
Unhandled Error
Error: Could not get code signature for running application
    at initUpdater (/Applications/JSUI.app/Contents/Resources/app.asar/node_modules/update-electron-app/index.js:47:15)
    at App.opts.electron.app.isReady.opts.electron.app.on (/Applications/JSUI.app/Contents/Resources/app.asar/node_modules/update-electron-app/index.js:32:43)

**Comment by kitze** [comment]
This release should be fine:
https://github.com/kitze/JSUI/releases/tag/v0.0.18

**Comment by mykel347** [comment]
Only the one with .zip works, the .dmg doesn't work and its v0.0.18
